// Major US Airports for ACARS/AMDAR Aircraft Soundings
// High-density airports have frequent ACARS observations

import { AircraftAirport } from './types';

export const ACARS_AIRPORTS: AircraftAirport[] = [
  // Major Hubs - High Density
  {
    icao: 'KATL',
    iata: 'ATL',
    name: 'Hartsfield-Jackson Atlanta International',
    city: 'Atlanta',
    state: 'GA',
    lat: 33.6407,
    lon: -84.4277,
    elevation_ft: 1026,
    typical_density: 'high',
  },
  {
    icao: 'KORD',
    iata: 'ORD',
    name: "O'Hare International",
    city: 'Chicago',
    state: 'IL',
    lat: 41.9742,
    lon: -87.9073,
    elevation_ft: 672,
    typical_density: 'high',
  },
  {
    icao: 'KDFW',
    iata: 'DFW',
    name: 'Dallas/Fort Worth International',
    city: 'Dallas',
    state: 'TX',
    lat: 32.8998,
    lon: -97.0403,
    elevation_ft: 607,
    typical_density: 'high',
  },
  {
    icao: 'KDEN',
    iata: 'DEN',
    name: 'Denver International',
    city: 'Denver',
    state: 'CO',
    lat: 39.8561,
    lon: -104.6737,
    elevation_ft: 5431,
    typical_density: 'high',
  },
  {
    icao: 'KJFK',
    iata: 'JFK',
    name: 'John F. Kennedy International',
    city: 'New York',
    state: 'NY',
    lat: 40.6413,
    lon: -73.7781,
    elevation_ft: 13,
    typical_density: 'high',
  },
  {
    icao: 'KLAX',
    iata: 'LAX',
    name: 'Los Angeles International',
    city: 'Los Angeles',
    state: 'CA',
    lat: 33.9425,
    lon: -118.4081,
    elevation_ft: 125,
    typical_density: 'high',
  },
  {
    icao: 'KSFO',
    iata: 'SFO',
    name: 'San Francisco International',
    city: 'San Francisco',
    state: 'CA',
    lat: 37.6213,
    lon: -122.3790,
    elevation_ft: 13,
    typical_density: 'high',
  },
  {
    icao: 'KLAS',
    iata: 'LAS',
    name: 'Harry Reid International',
    city: 'Las Vegas',
    state: 'NV',
    lat: 36.0840,
    lon: -115.1537,
    elevation_ft: 2181,
    typical_density: 'high',
  },
  {
    icao: 'KMCO',
    iata: 'MCO',
    name: 'Orlando International',
    city: 'Orlando',
    state: 'FL',
    lat: 28.4312,
    lon: -81.3081,
    elevation_ft: 96,
    typical_density: 'high',
  },
  {
    icao: 'KSEA',
    iata: 'SEA',
    name: 'Seattle-Tacoma International',
    city: 'Seattle',
    state: 'WA',
    lat: 47.4502,
    lon: -122.3088,
    elevation_ft: 433,
    typical_density: 'high',
  },
  {
    icao: 'KPHX',
    iata: 'PHX',
    name: 'Phoenix Sky Harbor International',
    city: 'Phoenix',
    state: 'AZ',
    lat: 33.4373,
    lon: -112.0078,
    elevation_ft: 1135,
    typical_density: 'high',
  },
  {
    icao: 'KMIA',
    iata: 'MIA',
    name: 'Miami International',
    city: 'Miami',
    state: 'FL',
    lat: 25.7959,
    lon: -80.2870,
    elevation_ft: 8,
    typical_density: 'high',
  },
  {
    icao: 'KEWR',
    iata: 'EWR',
    name: 'Newark Liberty International',
    city: 'Newark',
    state: 'NJ',
    lat: 40.6895,
    lon: -74.1745,
    elevation_ft: 18,
    typical_density: 'high',
  },
  {
    icao: 'KBOS',
    iata: 'BOS',
    name: 'Boston Logan International',
    city: 'Boston',
    state: 'MA',
    lat: 42.3656,
    lon: -71.0096,
    elevation_ft: 20,
    typical_density: 'high',
  },
  {
    icao: 'KMSP',
    iata: 'MSP',
    name: 'Minneapolis-Saint Paul International',
    city: 'Minneapolis',
    state: 'MN',
    lat: 44.8848,
    lon: -93.2223,
    elevation_ft: 841,
    typical_density: 'high',
  },
  {
    icao: 'KDTW',
    iata: 'DTW',
    name: 'Detroit Metropolitan Wayne County',
    city: 'Detroit',
    state: 'MI',
    lat: 42.2162,
    lon: -83.3554,
    elevation_ft: 645,
    typical_density: 'high',
  },
  {
    icao: 'KPHL',
    iata: 'PHL',
    name: 'Philadelphia International',
    city: 'Philadelphia',
    state: 'PA',
    lat: 39.8729,
    lon: -75.2437,
    elevation_ft: 36,
    typical_density: 'high',
  },
  {
    icao: 'KLGA',
    iata: 'LGA',
    name: 'LaGuardia',
    city: 'New York',
    state: 'NY',
    lat: 40.7769,
    lon: -73.8740,
    elevation_ft: 22,
    typical_density: 'high',
  },
  {
    icao: 'KFLL',
    iata: 'FLL',
    name: 'Fort Lauderdale-Hollywood International',
    city: 'Fort Lauderdale',
    state: 'FL',
    lat: 26.0742,
    lon: -80.1506,
    elevation_ft: 9,
    typical_density: 'high',
  },
  {
    icao: 'KIAD',
    iata: 'IAD',
    name: 'Washington Dulles International',
    city: 'Washington',
    state: 'DC',
    lat: 38.9531,
    lon: -77.4565,
    elevation_ft: 313,
    typical_density: 'high',
  },
  {
    icao: 'KDCA',
    iata: 'DCA',
    name: 'Ronald Reagan Washington National',
    city: 'Washington',
    state: 'DC',
    lat: 38.8512,
    lon: -77.0402,
    elevation_ft: 15,
    typical_density: 'high',
  },
  // Medium Density Airports
  {
    icao: 'KCLT',
    iata: 'CLT',
    name: 'Charlotte Douglas International',
    city: 'Charlotte',
    state: 'NC',
    lat: 35.2140,
    lon: -80.9431,
    elevation_ft: 748,
    typical_density: 'medium',
  },
  {
    icao: 'KSLC',
    iata: 'SLC',
    name: 'Salt Lake City International',
    city: 'Salt Lake City',
    state: 'UT',
    lat: 40.7884,
    lon: -111.9778,
    elevation_ft: 4227,
    typical_density: 'medium',
  },
  {
    icao: 'KSAN',
    iata: 'SAN',
    name: 'San Diego International',
    city: 'San Diego',
    state: 'CA',
    lat: 32.7336,
    lon: -117.1897,
    elevation_ft: 17,
    typical_density: 'medium',
  },
  {
    icao: 'KTPA',
    iata: 'TPA',
    name: 'Tampa International',
    city: 'Tampa',
    state: 'FL',
    lat: 27.9756,
    lon: -82.5333,
    elevation_ft: 26,
    typical_density: 'medium',
  },
  {
    icao: 'KPDX',
    iata: 'PDX',
    name: 'Portland International',
    city: 'Portland',
    state: 'OR',
    lat: 45.5898,
    lon: -122.5951,
    elevation_ft: 31,
    typical_density: 'medium',
  },
  {
    icao: 'KBWI',
    iata: 'BWI',
    name: 'Baltimore/Washington International',
    city: 'Baltimore',
    state: 'MD',
    lat: 39.1754,
    lon: -76.6683,
    elevation_ft: 146,
    typical_density: 'medium',
  },
  {
    icao: 'KSTL',
    iata: 'STL',
    name: 'St. Louis Lambert International',
    city: 'St. Louis',
    state: 'MO',
    lat: 38.7487,
    lon: -90.3700,
    elevation_ft: 618,
    typical_density: 'medium',
  },
  {
    icao: 'KAUS',
    iata: 'AUS',
    name: 'Austin-Bergstrom International',
    city: 'Austin',
    state: 'TX',
    lat: 30.1945,
    lon: -97.6699,
    elevation_ft: 542,
    typical_density: 'medium',
  },
  {
    icao: 'KHOU',
    iata: 'HOU',
    name: 'William P. Hobby',
    city: 'Houston',
    state: 'TX',
    lat: 29.6454,
    lon: -95.2789,
    elevation_ft: 46,
    typical_density: 'medium',
  },
  {
    icao: 'KIAH',
    iata: 'IAH',
    name: 'George Bush Intercontinental',
    city: 'Houston',
    state: 'TX',
    lat: 29.9902,
    lon: -95.3368,
    elevation_ft: 97,
    typical_density: 'high',
  },
  {
    icao: 'KMDW',
    iata: 'MDW',
    name: 'Chicago Midway International',
    city: 'Chicago',
    state: 'IL',
    lat: 41.7868,
    lon: -87.7522,
    elevation_ft: 620,
    typical_density: 'medium',
  },
  {
    icao: 'KBNA',
    iata: 'BNA',
    name: 'Nashville International',
    city: 'Nashville',
    state: 'TN',
    lat: 36.1263,
    lon: -86.6774,
    elevation_ft: 599,
    typical_density: 'medium',
  },
  {
    icao: 'KRDU',
    iata: 'RDU',
    name: 'Raleigh-Durham International',
    city: 'Raleigh',
    state: 'NC',
    lat: 35.8776,
    lon: -78.7875,
    elevation_ft: 435,
    typical_density: 'medium',
  },
  {
    icao: 'KMCI',
    iata: 'MCI',
    name: 'Kansas City International',
    city: 'Kansas City',
    state: 'MO',
    lat: 39.2976,
    lon: -94.7139,
    elevation_ft: 1026,
    typical_density: 'medium',
  },
  {
    icao: 'KCLE',
    iata: 'CLE',
    name: 'Cleveland Hopkins International',
    city: 'Cleveland',
    state: 'OH',
    lat: 41.4117,
    lon: -81.8498,
    elevation_ft: 791,
    typical_density: 'medium',
  },
  {
    icao: 'KSMF',
    iata: 'SMF',
    name: 'Sacramento International',
    city: 'Sacramento',
    state: 'CA',
    lat: 38.6954,
    lon: -121.5908,
    elevation_ft: 27,
    typical_density: 'medium',
  },
  {
    icao: 'KOAK',
    iata: 'OAK',
    name: 'Oakland International',
    city: 'Oakland',
    state: 'CA',
    lat: 37.7213,
    lon: -122.2208,
    elevation_ft: 9,
    typical_density: 'medium',
  },
  {
    icao: 'KSJC',
    iata: 'SJC',
    name: 'Norman Y. Mineta San Jose International',
    city: 'San Jose',
    state: 'CA',
    lat: 37.3626,
    lon: -121.9291,
    elevation_ft: 62,
    typical_density: 'medium',
  },
  {
    icao: 'KIND',
    iata: 'IND',
    name: 'Indianapolis International',
    city: 'Indianapolis',
    state: 'IN',
    lat: 39.7173,
    lon: -86.2944,
    elevation_ft: 797,
    typical_density: 'medium',
  },
  {
    icao: 'KCVG',
    iata: 'CVG',
    name: 'Cincinnati/Northern Kentucky International',
    city: 'Cincinnati',
    state: 'OH',
    lat: 39.0488,
    lon: -84.6678,
    elevation_ft: 896,
    typical_density: 'medium',
  },
  // Lower Density but Important for Coverage
  {
    icao: 'KMKE',
    iata: 'MKE',
    name: 'General Mitchell International',
    city: 'Milwaukee',
    state: 'WI',
    lat: 42.9472,
    lon: -87.8966,
    elevation_ft: 723,
    typical_density: 'low',
  },
  {
    icao: 'KPIT',
    iata: 'PIT',
    name: 'Pittsburgh International',
    city: 'Pittsburgh',
    state: 'PA',
    lat: 40.4915,
    lon: -80.2329,
    elevation_ft: 1203,
    typical_density: 'low',
  },
  {
    icao: 'KMSY',
    iata: 'MSY',
    name: 'Louis Armstrong New Orleans International',
    city: 'New Orleans',
    state: 'LA',
    lat: 29.9934,
    lon: -90.2580,
    elevation_ft: 4,
    typical_density: 'low',
  },
  {
    icao: 'KSAT',
    iata: 'SAT',
    name: 'San Antonio International',
    city: 'San Antonio',
    state: 'TX',
    lat: 29.5337,
    lon: -98.4698,
    elevation_ft: 809,
    typical_density: 'low',
  },
  {
    icao: 'KABQ',
    iata: 'ABQ',
    name: 'Albuquerque International Sunport',
    city: 'Albuquerque',
    state: 'NM',
    lat: 35.0402,
    lon: -106.6091,
    elevation_ft: 5355,
    typical_density: 'low',
  },
  {
    icao: 'KOMA',
    iata: 'OMA',
    name: 'Eppley Airfield',
    city: 'Omaha',
    state: 'NE',
    lat: 41.3032,
    lon: -95.8941,
    elevation_ft: 984,
    typical_density: 'low',
  },
  {
    icao: 'KOKC',
    iata: 'OKC',
    name: 'Will Rogers World',
    city: 'Oklahoma City',
    state: 'OK',
    lat: 35.3931,
    lon: -97.6007,
    elevation_ft: 1295,
    typical_density: 'low',
  },
  {
    icao: 'KTUL',
    iata: 'TUL',
    name: 'Tulsa International',
    city: 'Tulsa',
    state: 'OK',
    lat: 36.1984,
    lon: -95.8881,
    elevation_ft: 677,
    typical_density: 'low',
  },
  {
    icao: 'KBUF',
    iata: 'BUF',
    name: 'Buffalo Niagara International',
    city: 'Buffalo',
    state: 'NY',
    lat: 42.9405,
    lon: -78.7322,
    elevation_ft: 728,
    typical_density: 'low',
  },
  {
    icao: 'KPVD',
    iata: 'PVD',
    name: 'Rhode Island T. F. Green International',
    city: 'Providence',
    state: 'RI',
    lat: 41.7240,
    lon: -71.4283,
    elevation_ft: 55,
    typical_density: 'low',
  },
  {
    icao: 'KBDL',
    iata: 'BDL',
    name: 'Bradley International',
    city: 'Hartford',
    state: 'CT',
    lat: 41.9388,
    lon: -72.6832,
    elevation_ft: 173,
    typical_density: 'low',
  },
  {
    icao: 'KJAX',
    iata: 'JAX',
    name: 'Jacksonville International',
    city: 'Jacksonville',
    state: 'FL',
    lat: 30.4941,
    lon: -81.6879,
    elevation_ft: 30,
    typical_density: 'low',
  },
  {
    icao: 'KMEM',
    iata: 'MEM',
    name: 'Memphis International',
    city: 'Memphis',
    state: 'TN',
    lat: 35.0424,
    lon: -89.9767,
    elevation_ft: 341,
    typical_density: 'medium', // FedEx hub
  },
  {
    icao: 'KSDF',
    iata: 'SDF',
    name: 'Louisville Muhammad Ali International',
    city: 'Louisville',
    state: 'KY',
    lat: 38.1744,
    lon: -85.7360,
    elevation_ft: 501,
    typical_density: 'medium', // UPS hub
  },
  {
    icao: 'PANC',
    iata: 'ANC',
    name: 'Ted Stevens Anchorage International',
    city: 'Anchorage',
    state: 'AK',
    lat: 61.1743,
    lon: -149.9962,
    elevation_ft: 152,
    typical_density: 'medium', // Cargo hub
  },
  {
    icao: 'PHNL',
    iata: 'HNL',
    name: 'Daniel K. Inouye International',
    city: 'Honolulu',
    state: 'HI',
    lat: 21.3187,
    lon: -157.9225,
    elevation_ft: 13,
    typical_density: 'medium',
  },
];

// Get airports by density level
export function getAirportsByDensity(
  density: 'high' | 'medium' | 'low'
): AircraftAirport[] {
  return ACARS_AIRPORTS.filter((a) => a.typical_density === density);
}

// Get airport by ICAO code
export function getAirportByICAO(icao: string): AircraftAirport | undefined {
  return ACARS_AIRPORTS.find((a) => a.icao === icao.toUpperCase());
}

// Get airport by IATA code
export function getAirportByIATA(iata: string): AircraftAirport | undefined {
  return ACARS_AIRPORTS.find((a) => a.iata === iata.toUpperCase());
}

// Get nearest airport to a point
export function getNearestAirport(
  lat: number,
  lon: number
): AircraftAirport | null {
  let nearest: AircraftAirport | null = null;
  let minDist = Infinity;

  for (const airport of ACARS_AIRPORTS) {
    const dist = Math.sqrt(
      Math.pow(airport.lat - lat, 2) + Math.pow(airport.lon - lon, 2)
    );
    if (dist < minDist) {
      minDist = dist;
      nearest = airport;
    }
  }

  return nearest;
}

// Get CONUS airports only (exclude Alaska and Hawaii)
export const CONUS_AIRPORTS = ACARS_AIRPORTS.filter(
  (a) => !['AK', 'HI'].includes(a.state)
);

// Convert airports to GeoJSON
export function airportsToGeoJSON(): GeoJSON.FeatureCollection {
  return {
    type: 'FeatureCollection',
    features: ACARS_AIRPORTS.map((airport) => ({
      type: 'Feature' as const,
      properties: {
        icao: airport.icao,
        iata: airport.iata,
        name: airport.name,
        city: airport.city,
        state: airport.state,
        elevation_ft: airport.elevation_ft,
        density: airport.typical_density,
      },
      geometry: {
        type: 'Point' as const,
        coordinates: [airport.lon, airport.lat],
      },
    })),
  };
}
